version: "3.4"

services:
  server-api:
    build: ../api-server
    ports:
      - "8500:8500"

  client-api:
    ports:
      - "8501:8501"
    links:
      - "server-api:server-api"
    environment:
      - MY_SERVER_HOST=server-api
      - MY_SERVER_PORT=8500
      - MY_VALUE=http://server-api:8500
    build: .
