spring:
  application:
    name: eureka-service

server:
  port: 8502

eureka:
  dashboard:
    enabled: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
