spring:
  application:
    name: eureka-service

server:
  port: 8502

#eureka:
#  dashboard:
#    enabled: true
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    server:
#      waitTimeInMsWhenSyncEmpty: 0

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    api-server:
      stripPrefix: false
      path: /users/**
      url: ${USER_SERVER_ENDPOINT:http://localhost:8500}
    api-client:
      stripPrefix: false
      path: /analysis/**
      url: ${ANALYSIS_SERVER_ENDPOINT:http://localhost:8501}

