spring:
  application:
    name: api-server

server:
  port: 8500

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8502/eureka/
#  instance:
#    hostname: localhost